"use client";

import Link from "next/link";
import { ArrowRight, Activity } from "lucide-react";
import { useReadout } from "@/components/ui/LiveReadout";

/* ─── ECG waveform ──────────────────────────────────────────────
   One tile = flatline + a single beat spike. Strung into a strip and
   duplicated so animate-marquee (translateX 0 → -50%) loops seamlessly. */
function ecgPoints(beats: number, tile: number, mid: number, amp: number) {
  const p: string[] = [];
  for (let i = 0; i < beats; i++) {
    const x = i * tile;
    p.push(
      `${x},${mid}`,
      `${x + tile * 0.42},${mid}`,
      `${x + tile * 0.46},${mid - amp * 0.35}`,
      `${x + tile * 0.49},${mid + amp}`,
      `${x + tile * 0.52},${mid - amp * 1.15}`,
      `${x + tile * 0.55},${mid}`,
      `${x + tile},${mid}`,
    );
  }
  return p.join(" ");
}

function PulseStrip() {
  const beats = 8, tile = 120, w = beats * tile, h = 60, mid = 30, amp = 20;
  const pts = ecgPoints(beats, tile, mid, amp);
  // A plain element, not a nested component — defining a component during
  // render makes React recreate it on every pass.
  const half = (
    <svg width={w} height={h} viewBox={`0 0 ${w} ${h}`} className="shrink-0" preserveAspectRatio="none">
      <polyline points={pts} fill="none" stroke="var(--pulse-lime)" strokeWidth="1.5" strokeOpacity="0.6" />
    </svg>
  );
  return (
    <div className="relative w-full overflow-hidden" style={{ maskImage: "linear-gradient(90deg,transparent,#000 12%,#000 78%,transparent)" }}>
      {/* duplicated so the -50% marquee wraps seamlessly */}
      <div className="flex animate-marquee" style={{ width: "max-content" }}>
        {half}{half}
      </div>
      <Activity className="absolute right-[14%] top-1/2 -translate-y-1/2 w-6 h-6" style={{ color: "var(--pulse-cyan)" }} />
    </div>
  );
}

function MiniEcg({ color }: { color: string }) {
  const pts = ecgPoints(4, 60, 18, 13);
  return (
    <svg viewBox="0 0 240 36" className="w-full h-9" preserveAspectRatio="none">
      <polyline points={pts} fill="none" stroke={color} strokeWidth="1.75" />
    </svg>
  );
}

/* ─── Real SATTVIC content ──────────────────────────────────── */
// Counts are real: 145 meals in mealPool + 26 recipes in the browser = 171,
// and 12 badges in ALL_BADGES. "Meat-free" not "plant-based" — the pool uses
// paneer, curd, ghee and eggs, so a plant-based claim would be wrong.
const stats = [
  { num: "170+", label: "Vegetarian recipes" },
  { num: "7-Day", label: "Meal planning" },
  { num: "100%", label: "Meat-free" },
  { num: "12", label: "Achievement badges" },
];

const ticker = [
  "HIGH PROTEIN MEALS", "SATTVIC LIVING", "VEGETARIAN NUTRITION", "STREAK TRACKING",
  "MACRO TRACKING", "LOW CARB RECIPES", "MINDFUL EATING", "CLEAN INGREDIENTS",
];

const features = [
  { href: "/dashboard", tag: "Daily tracking", title: "Smart Dashboard", desc: "Live macro tracking, Sattvic Score, streak fire, water intake and Apple-style activity rings — one view." },
  { href: "/meal-planner", tag: "AI powered", title: "AI Meal Planner", desc: "One click. Your full week of vegetarian meals generated by AI, matched to your macro targets." },
  { href: "/recipes", tag: "Internet famous", title: "Viral Recipe Browser", desc: "20 tried-and-tested recipes from TikTok, Instagram, Reddit and YouTube. Food people actually make." },
  { href: "/macros", tag: "Personalised", title: "Macro Calculator", desc: "Height, weight, age, goal. Your exact personalised calorie and macro targets in seconds." },
  { href: "/dosha", tag: "Only on Sattvic", title: "Discover Your Dosha", desc: "7-question Ayurvedic quiz with allergy and condition tracking. Unlock your Vata, Pitta or Kapha plan." },
  { href: "/junk", tag: "Guilt-free", title: "Healthy Junk", desc: "Pizza, burgers, noodles? Get the vegetarian version that hits the same spot with fewer calories." },
  { href: "/workout", tag: "Burn calories", title: "Workout Tracker", desc: "Log workouts, pick intensity, get calories burned. Weekly burn summary and goal streaks." },
  { href: "/social", tag: "Social", title: "Compete with Friends", desc: "Add friends and battle it out on a weekly leaderboard. Challenges, badges, glory." },
];

/* Built-notes replace the invented testimonials that used to sit here. Sattvic
   has no user base yet, so quoting imaginary people was the one thing on this
   page that wasn't true — and a reviewer spots that instantly. */
const buildNotes = [
  { label: "The idea", text: "Most trackers ask you to count calories. Ayurveda asks what your body is like. Sattvic does both — a nine-question constitution read, then meals that hit real macro targets." },
  { label: "The hard part", text: "Plain-language food logging. \"2 rotis, dal, a glass of buttermilk\" has to become grams of protein — an LLM parses it, then the macros are recomputed and stored server-side." },
  { label: "The stack", text: "Next.js App Router on Vercel, MongoDB via Mongoose, Google auth with NextAuth, and Llama 3.3 70B on Groq for the AI paths. Built and shipped solo." },
  { label: "The cleanup", text: "A contrast pass measured every text pair against WCAG AA and fixed the ones that failed. The 3D hero and smooth-scroll switch off on touch devices, where they only cost frames." },
  { label: "Where AI stops", text: "A model turns your typed meal into grams — that's the fuzzy part. The score, the dosha match and the macro targets are deterministic functions, because a number you can't debug is a number you can't trust." },
  { label: "Built with AI, not by it", text: "AI-assisted on UI scaffolding and copy drafts. The product decisions, data model and nutrition logic are mine — and so is knowing which of those not to hand to a model." },
];

const accents = ["var(--pulse-lime)", "var(--pulse-cyan)", "var(--pulse-amber)"];
const card = "rounded-2xl border border-white/[0.08] bg-white/[0.03]";

export default function HomePage() {
  // null until mounted, and for visitors with nothing logged — the card then
  // shows the sample numbers instead of an empty shell.
  const live = useReadout();

  return (
    <div className="font-sans text-[#f1f0ed] bg-[#0a0b0a]" style={{ overflowX: "clip" }}>

      {/* ── HERO ─────────────────────────────────────────────── */}
      <section className="relative px-4 pt-16 pb-8 overflow-hidden">
        <div className="pointer-events-none absolute right-0 top-24 w-[46rem] h-[46rem] rounded-full animate-breathe"
          style={{ background: "radial-gradient(circle, rgba(194,240,74,0.10), transparent 60%)" }} />

        <div className="relative max-w-6xl mx-auto grid lg:grid-cols-[1.15fr_1fr] gap-12 items-start">
          <div className="space-y-7 pt-6">
            <span className="pulse-label inline-flex items-center gap-2 text-[11px] text-[#c2f04a] border border-[#c2f04a]/30 rounded-full px-4 py-1.5">
              Ayurvedic nutrition · 100% vegetarian
            </span>

            <h1 className="font-display text-[clamp(3.5rem,9vw,7rem)]">
              Eat with<br />intention.
            </h1>

            <p className="pulse-serif italic text-2xl md:text-3xl text-[#d8d8cf] leading-snug max-w-md">
              Not another meal tracker.
            </p>

            <p className="text-[15px] text-[#9aa0a6] leading-relaxed max-w-md">
              Sattvic uses Ayurvedic wisdom to build a nutrition plan that matches your body,
              your habits, your goals — warm, balanced, protein-honest vegetarian food, planned
              around your week.
            </p>

            <div className="flex flex-wrap items-center gap-3 pt-1">
              <Link href="/dosha?journey=1"
                className="pulse-label text-[13px] font-semibold text-[#0a0b0a] bg-[#c2f04a] hover:bg-[#d4ff5e] transition-colors rounded-full px-7 py-3.5">
                Start the journey
              </Link>
              <Link href="/recipes"
                className="pulse-label text-[13px] text-[#e8e8e0] border border-white/20 hover:border-white/40 transition-colors rounded-full px-7 py-3.5">
                Browse recipes
              </Link>
            </div>
            <p className="pulse-label text-[10px] text-[#6b7178]">Free to use · no calorie shaming · built around your body</p>
          </div>

          {/* RIGHT — dashboard read-out */}
          <div className="space-y-4">
            <div className={`${card} p-6`}>
              <div className="flex items-center justify-between pulse-label text-[10px] text-[#9aa0a6]">
                <span className="flex items-center gap-2">
                  <span className="w-1.5 h-1.5 rounded-full bg-[#c2f04a] animate-pulse" />
                  {live ? "Your score · today" : "Sattvic score · sample"}
                </span>
                <span className="text-[#c2f04a]">{live ? live.label : "On track"}</span>
              </div>
              <div className="flex items-end gap-4 mt-3">
                <span className="font-display text-[5.5rem] leading-none text-[#f1f0ed]">{live ? live.score : 78}</span>
                <div className="pulse-label text-[10px] text-[#9aa0a6] pb-3 leading-relaxed">
                  Streak<br />
                  <span className="text-[#c2f04a]">
                    {live ? `${live.streak} day${live.streak === 1 ? "" : "s"} strong` : "6 days strong"}
                  </span>
                </div>
              </div>
              <div className="mt-2"><MiniEcg color="var(--pulse-lime)" /></div>
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div className={`${card} p-5`}>
                <p className="pulse-label text-[10px] text-[#9aa0a6]">{live?.meal ? "Last logged" : "Tonight"}</p>
                <p className="pulse-serif text-2xl text-[#f1f0ed] mt-2 leading-tight line-clamp-3">
                  {live?.meal ?? "Paneer Tikka Bowl"}
                </p>
                <p className="pulse-label text-[9px] text-[#c2f04a] mt-3">
                  {live?.mealNote ?? "High protein · balanced"}
                </p>
              </div>
              <div className={`${card} p-5 flex flex-col`}>
                <p className="pulse-label text-[10px] text-[#9aa0a6]">Protein today</p>
                <p className="font-display text-5xl text-[#f1f0ed] mt-auto">
                  {live ? live.protein : 98}
                  <span className="text-lg text-[#9aa0a6]">/{live ? live.proteinTarget : 120}g</span>
                </p>
                <div className="mt-3 h-1.5 rounded-full bg-white/10 overflow-hidden">
                  <div className="h-full rounded-full bg-[#c2f04a]"
                    style={{ width: `${live ? Math.min(100, Math.round((live.protein / live.proteinTarget) * 100)) : 82}%` }} />
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="max-w-6xl mx-auto mt-10"><PulseStrip /></div>
      </section>

      {/* ── STATS ─────────────────────────────────────────────── */}
      <section className="px-4 py-20 max-w-6xl mx-auto">
        <div className="flex flex-wrap items-end justify-between gap-3 mb-10">
          <h2 className="font-display text-[clamp(2.5rem,6vw,4.5rem)] text-[#f1f0ed]">By the<br />numbers</h2>
          <span className="pulse-label text-[10px] text-[#9aa0a6]">100% vegetarian · Ayurveda-informed</span>
        </div>
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
          {stats.map((s, i) => (
            <div key={s.label} className={`${card} p-6 space-y-2`}>
              <p className="font-display text-[3.25rem] leading-none" style={{ color: accents[i % accents.length] }}>{s.num}</p>
              <p className="pulse-label text-[10px] text-[#9aa0a6]">{s.label}</p>
            </div>
          ))}
        </div>
      </section>

      {/* ── TICKER ────────────────────────────────────────────── */}
      <div className="border-y border-white/[0.06] py-3 overflow-hidden">
        <div className="flex animate-marquee whitespace-nowrap" style={{ width: "max-content" }}>
          {[...ticker, ...ticker].map((t, i) => (
            <span key={i} className="pulse-label text-[10px] text-[#6b7178] mx-6">{t} <span className="text-[#c2f04a] ml-6">+</span></span>
          ))}
        </div>
      </div>

      {/* ── FEATURES ──────────────────────────────────────────── */}
      <section className="px-4 py-20 max-w-6xl mx-auto">
        <div className="mb-10">
          <p className="pulse-label text-[10px] text-[#c2f04a] mb-3">Everything inside</p>
          <h2 className="font-display text-[clamp(2.5rem,6vw,4.5rem)] text-[#f1f0ed]">Eight tools.<br />One app.</h2>
        </div>
        <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">
          {features.map((f, i) => {
            const c = accents[i % accents.length];
            return (
              <Link key={f.href} href={f.href} className={`${card} group p-6 flex flex-col gap-3 transition-colors hover:border-white/20`}>
                <div className="flex items-center justify-between">
                  <span className="font-display text-2xl" style={{ color: c }}>{String(i + 1).padStart(2, "0")}</span>
                  <span className="pulse-label text-[9px] text-[#9aa0a6]">{f.tag}</span>
                </div>
                <h3 className="pulse-serif text-2xl text-[#f1f0ed] leading-tight">{f.title}</h3>
                <p className="text-xs text-[#8a9096] leading-relaxed flex-1">{f.desc}</p>
                <span className="pulse-label text-[10px] flex items-center gap-1.5" style={{ color: c }}>
                  Explore <ArrowRight className="w-3.5 h-3.5 group-hover:translate-x-1 transition-transform" />
                </span>
              </Link>
            );
          })}
        </div>
      </section>

      {/* ── HOW IT'S BUILT ────────────────────────────────────── */}
      <section className="px-4 py-16 max-w-6xl mx-auto">
        <div className="mb-10">
          <p className="pulse-label text-[10px] text-[#c2f04a] mb-3">How it&rsquo;s built</p>
          <h2 className="font-display text-[clamp(2.5rem,6vw,4.5rem)] text-[#f1f0ed]">No users yet.<br />Just the build.</h2>
          <p className="text-[15px] text-[#9aa0a6] leading-relaxed max-w-lg mt-5">
            Sattvic is a solo project, not a company — so there are no testimonials to show you.
            Here&rsquo;s what actually went into it instead.
          </p>
        </div>
        <div className="grid sm:grid-cols-2 gap-4">
          {buildNotes.map((n, i) => (
            <div key={n.label} className={`${card} p-6 space-y-3`}>
              <p className="pulse-label text-[10px]" style={{ color: accents[i % accents.length] }}>{n.label}</p>
              <p className="text-sm text-[#c8c8c0] leading-relaxed">{n.text}</p>
            </div>
          ))}
        </div>
        <div className="flex flex-wrap gap-3 mt-6">
          <a href="https://github.com/sam21270/sattvic" target="_blank" rel="noopener noreferrer"
            className="pulse-label text-[12px] text-[#0a0b0a] bg-[#c2f04a] hover:bg-[#d4ff5e] transition-colors rounded-full px-6 py-3">
            Read the code
          </a>
          <Link href="/dashboard"
            className="pulse-label text-[12px] text-[#e8e8e0] border border-white/20 hover:border-white/40 transition-colors rounded-full px-6 py-3">
            Try it with sample data
          </Link>
        </div>
      </section>

      {/* ── CTA ───────────────────────────────────────────────── */}
      <section className="px-4 py-24 text-center max-w-4xl mx-auto space-y-8">
        <h2 className="font-display text-[clamp(2.75rem,8vw,6rem)] text-[#f1f0ed]">
          Ready to eat with intention?
        </h2>
        <p className="text-[#9aa0a6] max-w-md mx-auto">
          Start your vegetarian wellness journey today. Free to use, built around your body.
        </p>
        <Link href="/dosha?journey=1"
          className="pulse-label inline-flex items-center gap-2 text-[13px] font-semibold text-[#0a0b0a] bg-[#c2f04a] hover:bg-[#d4ff5e] transition-colors rounded-full px-9 py-4">
          Start the journey <ArrowRight className="w-4 h-4" />
        </Link>
      </section>

      {/* ── FOOTER ────────────────────────────────────────────── */}
      <footer className="border-t border-white/[0.06] px-4 py-8 max-w-6xl mx-auto flex flex-wrap items-center justify-between gap-4 pulse-label text-[10px] text-[#6b7178]">
        <span>© 2026 Sattvic</span>
        <span className="flex gap-6">
          <Link href="/dashboard" className="hover:text-[#c2f04a] transition-colors">Dashboard</Link>
          <Link href="/macros" className="hover:text-[#c2f04a] transition-colors">Macros</Link>
          <Link href="/dosha" className="hover:text-[#c2f04a] transition-colors">Dosha</Link>
        </span>
      </footer>

    </div>
  );
}
