"use client";

import { useRef } from "react";
import Link from "next/link";
import dynamic from "next/dynamic";
import { motion, useScroll, useTransform, type Variants } from "framer-motion";
import { ArrowRight, Leaf, Sparkles, Star, Play } from "lucide-react";
import { ScrambleText } from "@/components/ui/ScrambleText";
import { FoodGallery } from "@/components/ui/FoodGallery";
import { AnimatedTerminal } from "@/components/ui/AnimatedTerminal";
import { CounterStat } from "@/components/ui/CounterStat";
import { MagneticButton } from "@/components/ui/MagneticButton";
import { BorderBeam } from "@/components/ui/BorderBeam";
import { JourneyRoadmap } from "@/components/ui/JourneyRoadmap";
import { TiltCard } from "@/components/ui/TiltCard";

const HeroOrbScene = dynamic(() => import("@/components/ui/HeroOrbScene"), {
  ssr: false,
  loading: () => (
    <div className="absolute inset-0 bg-[radial-gradient(ellipse_70%_50%_at_50%_30%,rgba(16,185,129,0.08)_0%,transparent_70%)]" />
  ),
});

/* ─── Ticker ───────────────────── */
const tickerItems = [
  "🥗 High Protein Meals",
  "🧘 Sattvic Living",
  "🌿 Plant-Based Nutrition",
  "🔥 Streak Tracking",
  "💪 Macro Tracking",
  "🫛 Low Carb Recipes",
  "✨ Mindful Eating",
  "🥦 Clean Ingredients",
];

/* ─── Stats ────────────────────── */
const stats = [
  { num: 200, suffix: "+", label: "Vegetarian Recipes" },
  { num: 7, suffix: "-Day", label: "Meal Planning" },
  { num: 100, suffix: "%", label: "Plant-Based" },
  { num: 12, suffix: "", label: "Achievement Badges" },
];

/* ─── Features ─────────────────── */
const features = [
  {
    href: "/dashboard",
    emoji: "📊",
    title: "Smart Dashboard",
    description: "Live macro tracking, Sattvic Score, streak fire, water intake, and Apple-style activity rings — all in one view.",
    tag: "Daily Tracking",
    color: "var(--ink-10b981)",
    bg: "rgba(16,185,129,0.10)",
    border: "rgba(16,185,129,0.20)",
    preview: ["🔥 78 Sattvic Score", "💧 1,800 ml water", "⚡ 6-day streak"],
  },
  {
    href: "/meal-planner",
    emoji: "🗓️",
    title: "AI Meal Planner",
    description: "One click. Your full week of vegetarian meals generated by AI, perfectly matched to your macro targets.",
    tag: "AI Powered",
    color: "var(--ink-8b5cf6)",
    bg: "rgba(139,92,246,0.10)",
    border: "rgba(139,92,246,0.20)",
    preview: ["Mon: Masala Oats + Dal", "Tue: Paneer Tikka Bowl", "Wed: Miso Ramen + Tofu"],
  },
  {
    href: "/recipes",
    emoji: "🍕",
    title: "Viral Recipe Browser",
    description: "20 tried-and-tested recipes from TikTok, Instagram, Reddit & YouTube. Real food people actually make.",
    tag: "Internet Famous",
    color: "var(--ink-f59e0b)",
    bg: "rgba(245,158,11,0.10)",
    border: "rgba(245,158,11,0.20)",
    preview: ["🔥 Baked Feta Pasta", "🔥 Chilli Oil Eggs", "🔥 Smashed Cucumbers"],
  },
  {
    href: "/macros",
    emoji: "🧮",
    title: "Macro Calculator",
    description: "Enter your height, weight, age and goal. Get your exact personalised calorie and macro targets in seconds.",
    tag: "Personalised",
    color: "var(--ink-f43f5e)",
    bg: "rgba(244,63,94,0.10)",
    border: "rgba(244,63,94,0.20)",
    preview: ["2,400 kcal target", "120g protein / day", "200g carbs / 65g fat"],
  },
  {
    href: "/dosha",
    emoji: "🌿",
    title: "Discover Your Dosha",
    description: "7-question Ayurvedic quiz with allergy and condition tracking. Unlock your Vata, Pitta or Kapha plan.",
    tag: "Only on SATTVIC",
    color: "var(--ink-a78bfa)",
    bg: "rgba(167,139,250,0.10)",
    border: "rgba(167,139,250,0.20)",
    preview: ["🌬️ Vata — light & creative", "🔥 Pitta — fiery & focused", "🌊 Kapha — grounded & calm"],
  },
  {
    href: "/junk",
    emoji: "🍔",
    title: "Healthy Junk",
    description: "Craving pizza, burgers, noodles? Get the vegetarian version that hits the same spot with fewer calories.",
    tag: "Guilt-Free",
    color: "var(--ink-f97316)",
    bg: "rgba(249,115,22,0.10)",
    border: "rgba(249,115,22,0.20)",
    preview: ["🍕 Cauliflower pizza", "🍔 Mushroom smash burger", "🍜 Dan dan noodles"],
  },
  {
    href: "/workout",
    emoji: "💪",
    title: "Workout Tracker",
    description: "Log workouts, pick intensity, get calories burned via MET formula. Weekly burn summary + goal streaks.",
    tag: "Burn Calories",
    color: "var(--ink-ef4444)",
    bg: "rgba(239,68,68,0.10)",
    border: "rgba(239,68,68,0.20)",
    preview: ["🏃 Running — 340 kcal", "🧘 Yoga — 120 kcal", "⚡ HIIT — 480 kcal"],
  },
  {
    href: "/social",
    emoji: "🏆",
    title: "Compete with Friends",
    description: "Create your profile, add friends, and battle it out on a weekly leaderboard. Challenges, badges, glory.",
    tag: "Social",
    color: "var(--ink-38bdf8)",
    bg: "rgba(56,189,248,0.10)",
    border: "rgba(56,189,248,0.20)",
    preview: ["👑 @priya_eats — 840 pts", "#2 @arjun_fit — 720 pts", "#3 @you — 610 pts"],
  },
];

/* ─── Reviews ──────────────────── */
const reviews = [
  {
    name: "Priya M.",
    handle: "@priya_eats",
    text: "Finally a meal planner that actually understands vegetarian nutrition. The suggestions are spot on!",
    stars: 5,
  },
  {
    name: "Arjun K.",
    handle: "@arjunfitlife",
    text: "I hit my protein goals every day now. The macro calculator changed how I plan my meals completely.",
    stars: 5,
  },
  {
    name: "Meera S.",
    handle: "@meerawellness",
    text: "The dosha quiz was eye-opening. My meal plan is completely different now and I feel so much better.",
    stars: 5,
  },
];

/* ─── Variants ─────────────────── */
const fadeUp: Variants = {
  hidden: { opacity: 0, y: 30 },
  show:   { opacity: 1, y: 0, transition: { duration: 0.6 } },
};

const stagger: Variants = {
  hidden: {},
  show:   { transition: { staggerChildren: 0.1 } },
};

export default function HomePage() {
  const heroRef = useRef(null);
  const { scrollYProgress } = useScroll({ target: heroRef, offset: ["start start", "end start"] });
  const heroY       = useTransform(scrollYProgress, [0, 1], ["0%", "25%"]);
  const heroOpacity = useTransform(scrollYProgress, [0, 0.8], [1, 0]);

  return (
    <div className="noise bg-[#0a0a0a]" style={{ overflowX: "clip" }}>

      {/* ── HERO ──────────────────────────────────── */}
      <section
        ref={heroRef}
        className="relative min-h-[95vh] flex flex-col items-center justify-center px-4 overflow-hidden"
      >
        {/* 3D interactive orb background */}
        <HeroOrbScene />
        {/* grid lines */}
        <div className="absolute inset-0 bg-[linear-gradient(rgba(255,255,255,0.02)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,0.02)_1px,transparent_1px)] bg-[size:64px_64px] pointer-events-none" />

        <motion.div
          style={{ y: heroY, opacity: heroOpacity }}
          className="relative z-10 max-w-6xl mx-auto w-full"
        >
          <div className="grid md:grid-cols-2 gap-16 items-center">

            {/* LEFT */}
            <div className="space-y-8">
              <motion.div
                initial={{ opacity: 0, scale: 0.9 }}
                animate={{ opacity: 1, scale: 1 }}
                transition={{ duration: 0.4 }}
                className="inline-flex items-center gap-2 bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 text-sm font-medium px-4 py-2 rounded-full"
              >
                <Sparkles className="w-3.5 h-3.5" />
                Ayurvedic Nutrition · 100% Vegetarian
              </motion.div>

              <motion.h1
                initial={{ opacity: 0, y: 24 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.15, duration: 0.6 }}
                className="text-5xl md:text-7xl font-bold text-white leading-[1.05] tracking-tighter"
              >
                <ScrambleText text="Eat with" delay={300} speed={35} className="block" />
                <ScrambleText text="intention." delay={700} speed={35} className="block text-emerald-400 italic" />
              </motion.h1>

              <motion.p
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.45, duration: 0.6 }}
                className="text-lg text-zinc-400 leading-relaxed max-w-md"
              >
                Not another meal tracker. SATTVIC uses Ayurvedic wisdom to build a nutrition plan that matches <em className="text-zinc-200 not-italic">your body</em>, your habits, your goals.
              </motion.p>

              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.6, duration: 0.5 }}
              >
                <MagneticButton strength={0.4}>
                  <Link
                    href="/dosha?journey=1"
                    className="group relative flex items-center gap-3 bg-emerald-500 text-white pl-5 pr-7 py-4 rounded-2xl font-bold text-base hover:bg-emerald-400 transition-all duration-300 shadow-xl shadow-emerald-900/50 w-fit"
                  >
                    <span className="relative flex items-center justify-center w-9 h-9 rounded-full bg-white/20">
                      <span className="absolute inset-0 rounded-full bg-white/30 animate-ping" />
                      <Play className="w-4 h-4 fill-white relative" />
                    </span>
                    <span className="flex flex-col items-start leading-tight">
                      <span>Start the Journey</span>
                      <span className="text-[11px] font-medium text-emerald-100/90">Dosha → Macros → Meal Plan → Dashboard</span>
                    </span>
                  </Link>
                </MagneticButton>
              </motion.div>

              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.75, duration: 0.5 }}
                className="flex flex-wrap gap-3"
              >
                <MagneticButton>
                  <Link
                    href="/dosha"
                    className="group flex items-center gap-2 bg-white/[0.06] text-zinc-200 px-6 py-3 rounded-2xl font-semibold text-sm border border-white/10 hover:border-white/20 hover:bg-white/[0.09] transition-all duration-300"
                  >
                    Take the Dosha quiz
                    <span className="text-[10px] text-zinc-500 font-normal">optional</span>
                    <ArrowRight className="w-3.5 h-3.5 group-hover:translate-x-1 transition-transform" />
                  </Link>
                </MagneticButton>
                <MagneticButton>
                  <Link
                    href="/recipes"
                    className="flex items-center gap-2 bg-white/[0.06] text-zinc-200 px-6 py-3 rounded-2xl font-semibold text-sm border border-white/10 hover:border-white/20 hover:bg-white/[0.09] transition-all duration-300"
                  >
                    Browse Recipes
                  </Link>
                </MagneticButton>
              </motion.div>

              {/* social proof */}
              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ delay: 0.9 }}
                className="flex items-center gap-3"
              >
                <div className="flex -space-x-2">
                  {["🧑🏽", "👩🏻", "🧑🏾", "👩🏼"].map((e, i) => (
                    <div key={i} className="w-8 h-8 rounded-full bg-zinc-800 border-2 border-[#0a0a0a] flex items-center justify-center text-sm">
                      {e}
                    </div>
                  ))}
                </div>
                <p className="text-sm text-zinc-500">
                  <span className="font-semibold text-zinc-200">2,400+</span> vegetarians eating better
                </p>
              </motion.div>
            </div>

            {/* RIGHT — animated terminal */}
            <motion.div
              initial={{ opacity: 0, x: 30 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: 0.3, duration: 0.8 }}
            >
              <AnimatedTerminal />
            </motion.div>

          </div>
        </motion.div>

        {/* scroll hint */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 1.4 }}
          className="absolute bottom-8 left-1/2 -translate-x-1/2 flex flex-col items-center gap-2 text-zinc-600"
        >
          <span className="text-xs tracking-widest uppercase">Scroll</span>
          <motion.div
            animate={{ y: [0, 6, 0] }}
            transition={{ repeat: Infinity, duration: 1.5 }}
            className="w-0.5 h-8 bg-gradient-to-b from-zinc-500 to-transparent rounded-full"
          />
        </motion.div>
      </section>

      {/* ── TICKER ───────────────────────────────── */}
      <div className="border-y border-white/[0.06] bg-white/[0.02] py-4 overflow-hidden">
        <div className="flex animate-marquee whitespace-nowrap">
          {[...tickerItems, ...tickerItems].map((item, i) => (
            <span key={i} className="mx-8 text-sm font-medium text-zinc-500 tracking-wide">
              {item}
            </span>
          ))}
        </div>
      </div>

      {/* ── STATS ─────────────────────────────────── */}
      <motion.section
        variants={stagger}
        initial="hidden"
        whileInView="show"
        viewport={{ once: true, margin: "-80px" }}
        className="py-20 px-4"
      >
        <div className="max-w-4xl mx-auto grid grid-cols-2 md:grid-cols-4 gap-4">
          {stats.map((s) => (
            <motion.div
              key={s.label}
              variants={fadeUp}
              className="text-center space-y-1 bg-white/[0.03] rounded-2xl border border-white/[0.06] py-8 px-4"
            >
              <p className="text-4xl font-bold text-white tracking-tight">
                <CounterStat value={s.num} suffix={s.suffix} duration={1600} />
              </p>
              <p className="text-sm text-zinc-500 font-medium">{s.label}</p>
            </motion.div>
          ))}
        </div>
      </motion.section>

      {/* ── JOURNEY ROADMAP ───────────────────────── */}
      <JourneyRoadmap />

      {/* ── FEATURES ──────────────────────────────── */}
      <section className="py-16 px-4">
        <div className="max-w-6xl mx-auto space-y-12">
          <motion.div variants={fadeUp} initial="hidden" whileInView="show" viewport={{ once: true }} className="text-center space-y-3">
            <span className="text-xs font-semibold tracking-widest text-emerald-500 uppercase">Everything inside</span>
            <h2 className="text-4xl md:text-5xl font-bold tracking-tight text-transparent bg-clip-text bg-gradient-to-r from-white via-emerald-300 to-white animate-gradient-text">
              Eight tools. One app.<br />Zero excuses.
            </h2>
          </motion.div>

          <motion.div
            variants={stagger} initial="hidden" whileInView="show" viewport={{ once: true, margin: "-60px" }}
            className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4"
          >
            {features.map((f, i) => (
              <motion.div key={f.href} variants={fadeUp}>
                <TiltCard maxTilt={8}>
                <Link href={f.href} className="group block relative rounded-2xl overflow-hidden transition-all duration-300"
                  style={{ background: "rgba(255,255,255,0.03)", border: `1px solid ${f.border}` }}>
                  <BorderBeam duration={3 + i * 0.4} colorFrom={f.color} colorTo={f.color} />

                  {/* top colour band */}
                  <div className="h-1 w-full" style={{ background: `linear-gradient(90deg, ${f.color}, transparent)` }} />

                  <div className="p-5 space-y-4">
                    {/* icon + tag */}
                    <div className="flex items-start justify-between">
                      <div className="w-11 h-11 rounded-2xl flex items-center justify-center text-2xl"
                        style={{ background: f.bg, border: `1px solid ${f.border}` }}>
                        {f.emoji}
                      </div>
                      <span className="text-[10px] font-semibold px-2 py-1 rounded-full"
                        style={{ background: f.bg, color: f.color, border: `1px solid ${f.border}` }}>
                        {f.tag}
                      </span>
                    </div>

                    {/* title + desc */}
                    <div>
                      <h3 className="font-bold text-white text-base leading-tight mb-1.5 group-hover:opacity-90 transition-opacity">{f.title}</h3>
                      <p className="text-zinc-500 text-xs leading-relaxed">{f.description}</p>
                    </div>

                    {/* preview list */}
                    <div className="space-y-1.5 py-3 border-y" style={{ borderColor: f.border }}>
                      {f.preview.map((line) => (
                        <p key={line} className="text-[11px] font-medium" style={{ color: f.color }}>{line}</p>
                      ))}
                    </div>

                    {/* CTA */}
                    <div className="flex items-center gap-1.5 text-xs font-semibold transition-all" style={{ color: f.color }}>
                      Explore
                      <ArrowRight className="w-3.5 h-3.5 group-hover:translate-x-1 transition-transform" />
                    </div>
                  </div>
                </Link>
                </TiltCard>
              </motion.div>
            ))}
          </motion.div>
        </div>
      </section>


      {/* ── TESTIMONIALS ──────────────────────────── */}
      <section className="py-24 px-4">
        <div className="max-w-5xl mx-auto">
          <motion.div
            variants={fadeUp}
            initial="hidden"
            whileInView="show"
            viewport={{ once: true }}
            className="text-center mb-12 space-y-3"
          >
            <span className="text-xs font-semibold tracking-widest text-emerald-500 uppercase">Loved by vegetarians</span>
            <h2 className="text-4xl font-bold text-white tracking-tight">Real people, real results.</h2>
          </motion.div>

          {/* infinite marquee — pauses on hover */}
          <div className="relative overflow-hidden" style={{ maskImage: "linear-gradient(90deg, transparent, black 8%, black 92%, transparent)" }}>
            <div className="flex gap-4 w-max animate-marquee-slow">
              {[...reviews, ...reviews, ...reviews, ...reviews].map((r, i) => (
                <div
                  key={`${r.name}-${i}`}
                  className="w-80 shrink-0 bg-white/[0.03] border border-white/[0.07] rounded-2xl p-6 space-y-4 hover:border-emerald-500/25 transition-colors"
                >
                  <div className="flex gap-1">
                    {Array.from({ length: r.stars }).map((_, s) => (
                      <Star key={s} className="w-4 h-4 fill-amber-400 text-amber-400" />
                    ))}
                  </div>
                  <p className="text-zinc-400 leading-relaxed text-sm">"{r.text}"</p>
                  <div>
                    <p className="font-semibold text-zinc-200 text-sm">{r.name}</p>
                    <p className="text-zinc-600 text-xs">{r.handle}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* ── GALLERY ───────────────────────────────── */}
      <FoodGallery />

      {/* ── CTA BANNER ────────────────────────────── */}
      <section className="py-10 px-4 pb-24">
        <motion.div
          variants={fadeUp}
          initial="hidden"
          whileInView="show"
          viewport={{ once: true }}
          className="relative max-w-4xl mx-auto bg-white/[0.03] border border-emerald-500/20 rounded-[2rem] p-12 text-center space-y-6 overflow-hidden"
        >
          {/* glow */}
          <div className="absolute inset-0 bg-[radial-gradient(ellipse_60%_50%_at_50%_50%,rgba(16,185,129,0.08),transparent)] pointer-events-none" />

          <Leaf className="relative w-10 h-10 mx-auto text-emerald-400 opacity-80" />
          <h2 className="relative text-4xl md:text-5xl font-bold tracking-tight text-transparent bg-clip-text bg-gradient-to-r from-white via-emerald-300 to-white animate-gradient-text">
            Ready to eat with intention?
          </h2>
          <p className="relative text-zinc-400 text-lg max-w-xl mx-auto">
            Start your vegetarian wellness journey today. Free to use, built around your body.
          </p>
          <Link
            href="/macros"
            className="relative inline-flex items-center gap-2 bg-emerald-500 text-white px-8 py-4 rounded-2xl font-bold text-lg hover:bg-emerald-400 transition-colors shadow-lg shadow-emerald-900/30 overflow-hidden"
          >
            <span aria-hidden className="absolute inset-y-0 w-1/3 bg-gradient-to-r from-transparent via-white/30 to-transparent animate-shimmer" />
            Calculate My Macros <ArrowRight className="w-5 h-5" />
          </Link>
        </motion.div>
      </section>

    </div>
  );
}
